apps/book/urls.py
from django.urls import path
from apps.book import views

app_name = "book"


urlpatterns = [
    path("community/", views.CommunityListView.as_view(), name="community"),
    path("lost-animal-list/", views.LostAnimalListView.as_view(), name="lost-animal-list"),
    path("lost-animal/", views.post_lost_animal, name="lost-animal"),
    path(
        "lost-animal/detail/<int:id>",
        views.LostAnimalDetail.as_view(),
        name="lost-animal-detail",
    ),
]

apps/common/urls.py
from django.urls import path, include
from apps.common import views


app_name = "common"

urlpatterns = [

    path("", views.HomeView.as_view(), name="home"),
    # path("contact", views.contact, name="contact"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("post/<int:id>", views.PostDetail.as_view(), name="post"),
    path("event/", views.EventListView.as_view(), name="event"),
    path("location/<int:id>", views.LocationsView.as_view(), name="location"),
    path(
        "location/detail/<int:id>",
        views.LocationDetailView.as_view(),
        name="location-detail",
    ),
    path('save_position/<int:position_id>/', views.save_position, name='save_position'),
    path('unsave_position/<int:position_id>/', views.unsave_position, name='unsave_position'),
    path("saved/", views.UserSavedView.as_view(), name="user_saved")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from django.conf.urls.i18n import set_language
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import TemplateView  # new

from django.contrib.auth.forms import AuthenticationForm
from core.routers import app


def configure_admin_login():
    if settings.DEBUG:
        return

    # captcha
    from django_recaptcha import fields

    class LoginForm(AuthenticationForm):
        captcha = fields.ReCaptchaField()

        def clean(self):
            captcha = self.cleaned_data.get("captcha")
            if not captcha:
                return
            return super().clean()

    admin.site.login_form = LoginForm
    admin.site.login_template = "login.html"


configure_admin_login()


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("admin/", admin.site.urls),
    path("set_language/", set_language, name="set_language"),
    path("sentry-debug/", trigger_error),
    path("accounts/", include("allauth.urls")),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("api/v1/", app.urls),
]

urlpatterns += i18n_patterns(path("", include("apps.common.urls")))
urlpatterns += i18n_patterns(path("", include("apps.book.urls")))

if settings.DEBUG:
    urlpatterns += [path("__reload__/", include("django_browser_reload.urls"))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layout/footer.html
{% load static i18n %}


<footer class="bg-zinc-900 grid grid-cols-1 pt-7 mt-auto">
    
    <div class="flex items-center justify-center">
      <img class="justify-center items-end h-14" style="border-radius: 100%;" src="{% static 'opasi.jpg' %}" alt="logo" >
  
    </div>

    <div class="mt-3">
      <ul
          class="flex flex-col justify-center font-medium p-4 md:p-0 mt-4 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0">
          <li>
            <a href="{% url 'common:about' %}" class="block py-2 px-3 md:p-0 text-white rounded md:bg-transparent hover:text-blue-700
              opacity-50">{% trans 'About' %}</a>
          </li>
          <li>
            <a href="#" class="block py-2 px-3 md:p-0 text-white rounded md:bg-transparent hover:text-blue-700
              opacity-50">Cookie fayllari siyosati</a>
          </li>
          <li>
            <a href="#" class="block py-2 px-3 md:p-0 text-white rounded md:bg-transparent hover:text-blue-700
              opacity-50">Foydalanish qoidalari</a>
          </li>
        </ul>
    </div>

    <div class="flex justify-center space-x-5 md:mt-4">
      <i class="fa-brands fa-instagram"></i>
      <i class="fa-brands fa-telegram"></i>
      <i class="fa-brands fa-youtube"></i>
      <i class="fa-brands fa-twitter"></i>
      <i class="fa-brands fa-facebook"></i>
    </div>
  
    <div class="border-3 border-black mt-2 p-3 mx-3 justify-between flex">
      <p class="">@ kedi.uz. All rights reserved</p>

    </div>
  </footer>

templates/layout/header.html
{% load static i18n %}

<div class="bg-zinc-900 sticky top-0 z-50">
  <nav class="border-gray-200 ">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="{% url 'common:home' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
          <img src="{% static 'opasi.jpg' %}" style="border-radius: 100%;" class="h-10" alt="Logo" />
        </a>
      <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">

        <form action="{% url 'set_language' %}" method="post" class="mr-2">
          {% csrf_token %}
          
          <!-- Language Dropdown -->
          <div class="relative w-full bg-black">
            <select name="language" onchange="this.form.submit()" class="bg-black text-white border-none block py-3 w-32 cursor-pointer focus:border-zinc-900 border-zinc-900 appearance-none focus:ring-0 rounded-sm">
              {% get_current_language as LANGUAGE_CODE %}
              {% get_available_languages as LANGUAGES %}
        
              {% for lang in LANGUAGES %}
                <option value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %}selected{% endif %}>
                  {{ lang.1 }}
                </option>
              {% endfor %}
            </select>
        
            <!-- Ensure the current path is maintained after language selection -->
            <input type="hidden" name="next" value="{{ request.path }}">
          </div>
        </form>
        

        {% if user.is_authenticated %}
          {% if socialaccount_obj %}
            {% for account in socialaccount_obj %}
              {% if account.provider == 'google' %}
              <button type="button" class="flex text-sm bg-gray-800 rounded-full focus:ring-4 focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
                <span class="sr-only">Open user menu</span>
                <img class="w-8 h-8 rounded-full" src="{{ account.extra_data.picture }}" alt="user photo">
              </button>
              <!-- Dropdown menu -->
              <div class="z-50 hidden my-4 text-base list-none divide-y rounded-lg shadow bg-gray-700 divide-gray-600" id="user-dropdown">
                <div class="px-4 py-3">
                  <span class="block text-sm text-white">{{ user.username }}</span>
                  <span class="block text-sm truncate text-gray-400">{{ user.email }}</span>
                </div>
                <ul class="py-2" aria-labelledby="user-menu-button">
                  {% if request.user.is_authenticated %}
                  <li>
                    <a href="{% url 'common:user_saved' %}" class="block px-4 py-2 text-sm hover:bg-gray-600 text-gray-200 hover:text-white">Saved</a>
                  </li>
                  {% endif %}
                  <li>
                    <a href="{% url 'account_logout' %}" class="block px-4 py-2 text-sm hover:bg-gray-600 text-gray-200 hover:text-white">Sign Out</a>
                  </li>
                </ul>
              </div>
              {% endif %}
            {% endfor %}
          {% endif %}
        {% else %}
          <a href="{% url 'account_login' %}">
            <button type="button" class="text-white hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-500 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
              Kirish
            </button>
          </a>
        {% endif %}
        
        <!-- Hamburger menu button -->
        <button data-collapse-toggle="navbar-user" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm rounded-lg md:hidden focus:outline-none focus:ring-2 text-gray-400 hover:bg-gray-700 focus:ring-gray-600" aria-controls="navbar-user" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
          </svg>
        </button>
      </div>

      <!-- Mobile menu -->
      <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
        <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border rounded-lg md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 border-gray-700">
          <li>
            <a href="{% url 'common:home' %}" class="block py-2 px-3 text-red rounded md:bg-transparent md:p-0 hove:text-blue-500" aria-current="page">{% trans 'Home' %}</a>
          </li>
          <li>
            <a href="{% url 'common:about' %}" class="block py-2 px-3 rounded md:hover:bg-transparent md:p-0 text-white hover:text-blue-500 hover:bg-gray-700">{% trans 'About' %}</a>
          </li>
          <li>
            <a href="{% url 'common:event' %}" class="block py-2 px-3 rounded md:hover:bg-transparent md:p-0 text-white md:hover:text-blue-500 hover:bg-gray-700 hover:text-white">{% trans 'Event' %}</a>
          </li>
          <li>
            <a href="{% url 'book:community' %}" class="block py-2 px-3 rounded md:hover:bg-transparent md:p-0 text-white md:hover:text-blue-500 hover:bg-gray-700 hover:text-white">{% trans 'Nature team'%}</a>
          </li>
          <li>
            <a href="{% url 'book:lost-animal-list' %}" class="block py-2 px-3 rounded md:hover:bg-transparent md:p-0 text-white md:hover:text-blue-500 hover:bg-gray-700 hover:text-white">{% trans 'Lost pet' %}</a>
          </li>
          <li>
            <a href="{% url 'book:lost-animal' %}" class="block py-2 px-3 rounded md:hover:bg-transparent md:p-0 text-white md:hover:text-blue-500 hover:bg-gray-700 hover:text-white">{% trans 'Report lost pet' %}
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>